version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user_name
      POSTGRES_PASSWORD: db_user_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Django Backend
  backend:
    build: ./backend
    environment:
      DATABASE_URL: database_url
      SECRET_KEY: your-secret-key
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  # React Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
